-- MySQL Script generated by MySQL Workbench
-- qua 17 mai 2023 22:05:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancodedados
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pokedex` ;

-- -----------------------------------------------------
-- Schema bancodedados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokedex` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pokedex` ;

-- -----------------------------------------------------
-- Table `pokedex`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pokedex`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`especie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pokedex`.`habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`habilidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pokedex`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pokedex`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`pokemon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `altura` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  `valor_ataque` DOUBLE NOT NULL,
  `valor_defesa` DOUBLE NOT NULL,
  `velocidade_media` DOUBLE NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_especie` INT NOT NULL,
  `tipo_primario` INT NOT NULL,
  `tipo_secundario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `id_especie_idx` (`id_especie` ASC) VISIBLE,
  INDEX `tipo_primario_idx` (`tipo_primario` ASC) VISIBLE,
  INDEX `tipo_secundario_idx` (`tipo_secundario` ASC) VISIBLE,
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pokedex`.`categoria` (`id`),
  CONSTRAINT `id_especie`
    FOREIGN KEY (`id_especie`)
    REFERENCES `pokedex`.`especie` (`id`),
  CONSTRAINT `tipo_primario`
    FOREIGN KEY (`tipo_primario`)
    REFERENCES `pokedex`.`tipo` (`id`),
  CONSTRAINT `tipo_secundario`
    FOREIGN KEY (`tipo_secundario`)
    REFERENCES `pokedex`.`tipo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pokedex`.`pokemon_habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex`.`pokemon_habilidade` (
  `pokemon_id` INT NOT NULL,
  `habilidade_id` INT NOT NULL,
  `oculta` TINYINT NOT NULL,
  INDEX `pokemon_id_idx` (`pokemon_id` ASC) VISIBLE,
  INDEX `habilidade_id_idx` (`habilidade_id` ASC) VISIBLE,
  CONSTRAINT `habilidade_id`
    FOREIGN KEY (`habilidade_id`)
    REFERENCES `pokedex`.`habilidade` (`id`),
  CONSTRAINT `pokemon_id`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pokedex`.`pokemon` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



